version: '3.8'

services:
  # Drupal service
  drupal:
    build: .
    container_name: drupal
    ports:
      - "8080:80"
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupal
    restart: always
    depends_on:
      - db

  # MySQL database service
  db:
    image: mysql:8.0
    container_name: drupal_db
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
